[theme]
primaryColor = "#e63946"
backgroundColor = "#1a1a2e"
secondaryBackgroundColor = "#16213e"
textColor = "#edf2f4"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
